"""Filtro anti-slop heurístico (sem custo de API) para o pipeline do scraper.

Objetivo: impedir que conteúdo majoritariamente "slop" (texto gerado por IA,
genérico, vazio, clickbait) entre no feed semanal de IA criativa.

A decisão combina DOIS sinais, calculados sem nenhuma chamada de API:

1. SINAL DOS COMENTÁRIOS (peso maior — é validação humana):
   procura nos `top_comments` por marcadores de rejeição da comunidade
   ("slop", "ai-generated", "low effort", etc). Quanto mais comentários — e
   especialmente quanto mais upvotados — chamam o post de slop, maior o sinal.
   Comentário crítico com score alto, ou net score negativo dos top comments,
   também reforçam o sinal.

2. SINAL DO TEXTO (peso menor — heurística de "escrito por IA / genérico")
   sobre `title` + `body_md`: frases de transição típicas de LLM, estrutura
   listicle vazia, densidade anormal de em-dash e adjetivos de marketing,
   falta de especificidade técnica em texto longo, e texto curto + clickbait.

Os dois sinais (cada um normalizado em 0..1) são combinados por média
ponderada num score final 0..1. Acima de `SLOP_THRESHOLD` o post é
considerado majoritariamente slop.

RACIONAL DOS PESOS
------------------
Comentários pesam mais (COMMENT_WEIGHT > TEXT_WEIGHT) porque humanos chamando
o post de slop é o sinal mais confiável que temos — heurística de texto sozinha
gera falsos positivos (posts técnicos legítimos podem usar "furthermore" etc).
Por isso o threshold (0.6) é calibrado de modo que:
  - vários comentários humanos chamando de slop já bastam para barrar;
  - só a heurística de texto, isolada, raramente cruza o threshold sozinha
    (precisa de um texto MUITO genérico), evitando barrar posts técnicos bons.

Todos os léxicos, pesos e thresholds são CONSTANTES no topo do módulo,
fáceis de ajustar.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# CONSTANTES AJUSTÁVEIS
# ---------------------------------------------------------------------------

# Threshold final: score >= este valor => is_slop=True.
SLOP_THRESHOLD: float = 0.6

# Pesos da combinação dos dois sinais (devem somar 1.0).
COMMENT_WEIGHT: float = 0.65  # validação humana vale mais
TEXT_WEIGHT: float = 0.35

# --- Sinal de comentários -------------------------------------------------

# Marcadores de rejeição da comunidade (substring match, case-insensitive).
COMMENT_SLOP_MARKERS: tuple[str, ...] = (
    "ai slop",
    "ai-generated",
    "ai generated",
    "this is ai",
    "written by ai",
    "chatgpt wrote",
    "wrote this with chatgpt",
    "generated by chatgpt",
    "slop",
    "low effort",
    "low-effort",
    "word salad",
    "hallucinat",  # hallucinate / hallucination / hallucinated
    "nonsense",
    "generic",
    "spam",
    "this is a bot",
    "bot post",
    "obviously ai",
    "clearly ai",
    "smells like ai",
    "reads like ai",
)

# Marcadores mais fracos: só contam como slop se também houver contexto de IA.
# (palavras como "bot" sozinhas são ambíguas demais para barrar por si só)
COMMENT_WEAK_MARKERS: tuple[str, ...] = (
    "bot",
)

# Quantos comentários "slop" (peso 1.0 cada) saturam o sinal em 1.0.
# 2 humanos concordando que é slop já é forte; 3 satura.
COMMENT_SLOP_SATURATION: float = 3.0

# Comentário crítico altamente upvotado conta mais. Acima deste score, um
# comentário slop vale "extra" (até +1.0 de peso adicional).
COMMENT_HIGH_SCORE: int = 20

# Net score (soma de score) dos top comments abaixo deste valor sugere
# rejeição geral da comunidade — adiciona um empurrão ao sinal.
COMMENT_NET_NEGATIVE: int = -5

# --- Sinal de texto -------------------------------------------------------

# Frases de transição / marketing típicas de LLM (substring, case-insensitive).
LLM_FILLER_PHRASES: tuple[str, ...] = (
    "in conclusion",
    "it's important to note",
    "it is important to note",
    "in today's fast-paced",
    "in the world of",
    "dive into",
    "delve into",
    "unleash",
    "unlock the power",
    "game-changer",
    "game changer",
    "revolutionize",
    "harness the power",
    "in summary",
    "furthermore",
    "moreover",
    "this article",
    "let's explore",
    "the realm of",
    "ever-evolving",
    "ever evolving",
    "landscape of",
    "in the realm of",
    "when it comes to",
    "at the end of the day",
    "the power of",
)

# Adjetivos / buzzwords de marketing (match por palavra inteira).
MARKETING_ADJECTIVES: tuple[str, ...] = (
    "cutting-edge",
    "cutting edge",
    "state-of-the-art",
    "groundbreaking",
    "seamless",
    "seamlessly",
    "robust",
    "powerful",
    "innovative",
    "revolutionary",
    "transformative",
    "next-level",
    "next level",
    "unparalleled",
    "unprecedented",
    "supercharge",
    "elevate",
    "empower",
    "leverage",
    "synergy",
    "holistic",
)

# Termos concretos que indicam especificidade técnica (presença => NÃO slop).
TECHNICAL_TOKENS_RE = re.compile(
    r"(```|\bcfg\b|\bcfg_scale\b|\bsteps?\b|\bseed\b|\bsampler\b|\blora\b|"
    r"\bcheckpoint\b|\bvram\b|\bgpu\b|\bfp16\b|\bfp8\b|\bggml\b|\bgguf\b|"
    r"\bparams?\b|\bparameters?\b|\bcomfyui\b|\bworkflow\b|\bcontrolnet\b|"
    r"\bdiffusion\b|\bprompt\b|\btoken[s]?\b|\bbatch\b|\bepoch\b|\bdataset\b|"
    r"\bbenchmark\b|\bapi\b|\bversion\b|\bv\d+(\.\d+)?\b|\bb\b\d|\d+x\d+|"
    r"\$\d|\d+\s?(?:gb|mb|tb|ms|fps|hz|w|b|k|m)\b|\bhttps?://)",
    re.IGNORECASE,
)

# Nomes/famílias de modelos comuns (especificidade => NÃO slop).
MODEL_NAME_RE = re.compile(
    r"\b(gpt-?\d|claude|gemini|llama|mistral|mixtral|qwen|deepseek|flux|"
    r"sdxl|stable\s?diffusion|sd\d|midjourney|dall-?e|sora|runway|kling|"
    r"veo|wan|hunyuan|pika|suno|udio|whisper|sonnet|opus|haiku|grok)\b",
    re.IGNORECASE,
)

EM_DASH_RE = re.compile(r"[—–]")  # em-dash e en-dash
WORD_RE = re.compile(r"\b\w+\b")
BULLET_RE = re.compile(r"^\s*(?:[-*•]|\d+[.)])\s+", re.MULTILINE)

# A partir de quantas palavras consideramos o texto "longo" (e então cobramos
# especificidade técnica).
LONG_TEXT_WORDS: int = 120

# Clickbait no título: marcadores típicos.
CLICKBAIT_RE = re.compile(
    r"(you won't believe|this one trick|shocking|mind-?blowing|"
    r"will change everything|must-?have|the truth about|here's why|"
    r"what nobody tells you|game[- ]?chang|secret|insane|ultimate guide|"
    r"everything you need to know|\d+\s+(?:ways|tips|tricks|reasons|things))",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# SINAL DOS COMENTÁRIOS
# ---------------------------------------------------------------------------

def _comment_signal(top_comments: list | None) -> tuple[float, list[str]]:
    """Calcula o sinal de slop a partir dos comentários (0..1) + razões."""
    reasons: list[str] = []
    if not top_comments:
        return 0.0, reasons

    slop_weight = 0.0
    slop_hits = 0
    net_score = 0
    high_score_critic = False

    for c in top_comments:
        if not isinstance(c, dict):
            continue
        body = (c.get("body") or "").lower()
        try:
            cscore = int(c.get("score") or 0)
        except (TypeError, ValueError):
            cscore = 0
        net_score += cscore

        if not body:
            continue

        is_critic = any(m in body for m in COMMENT_SLOP_MARKERS)
        if not is_critic:
            # marcadores fracos só contam junto de contexto de IA
            if any(m in body for m in COMMENT_WEAK_MARKERS) and (
                "ai" in body or "generat" in body or "gpt" in body
            ):
                is_critic = True

        if is_critic:
            slop_hits += 1
            # comentário upvotado pesa mais: base 1.0 + bônus por upvotes
            weight = 1.0
            if cscore >= COMMENT_HIGH_SCORE:
                weight += min(cscore / (COMMENT_HIGH_SCORE * 4.0), 1.0)
                high_score_critic = True
            slop_weight += weight

    if slop_hits == 0:
        # Mesmo sem marcadores explícitos, net score muito negativo é sinal fraco.
        if net_score <= COMMENT_NET_NEGATIVE:
            reasons.append(
                f"comentários top com net score negativo ({net_score})"
            )
            return 0.25, reasons
        return 0.0, reasons

    score = min(slop_weight / COMMENT_SLOP_SATURATION, 1.0)

    reasons.append(
        f"{slop_hits} comentário(s) chamando de slop/IA "
        f"(peso={slop_weight:.1f})"
    )
    if high_score_critic:
        reasons.append("comentário crítico altamente upvotado")
    if net_score <= COMMENT_NET_NEGATIVE:
        reasons.append(f"net score negativo dos top comments ({net_score})")
        score = min(score + 0.1, 1.0)

    return score, reasons


# ---------------------------------------------------------------------------
# SINAL DO TEXTO
# ---------------------------------------------------------------------------

def _text_signal(title: str | None, body_md: str | None) -> tuple[float, list[str]]:
    """Calcula o sinal de slop a partir do texto (0..1) + razões."""
    reasons: list[str] = []
    title = (title or "").strip()
    body = (body_md or "").strip()
    full = f"{title}\n{body}".strip()

    if not full:
        # Sem texto nenhum não dá para avaliar texto — sinal neutro/baixo.
        return 0.0, reasons

    full_lower = full.lower()
    words = WORD_RE.findall(full)
    n_words = len(words)

    points = 0.0  # acumulador de "pontos de slop" do texto

    # 1. Frases de transição genéricas de LLM.
    filler_hits = sum(1 for p in LLM_FILLER_PHRASES if p in full_lower)
    if filler_hits:
        points += min(filler_hits, 4) * 0.18
        reasons.append(f"{filler_hits} frase(s) genérica(s) de LLM")

    # 2. Adjetivos de marketing.
    marketing_hits = sum(1 for a in MARKETING_ADJECTIVES if a in full_lower)
    if marketing_hits:
        points += min(marketing_hits, 4) * 0.12
        reasons.append(f"{marketing_hits} adjetivo(s) de marketing")

    # 3. Densidade anormal de em-dash (típico de texto de LLM).
    em_dashes = len(EM_DASH_RE.findall(full))
    if n_words >= 40 and em_dashes >= 3:
        density = em_dashes / max(n_words / 100.0, 1.0)  # por ~100 palavras
        if density >= 1.5:
            points += 0.2
            reasons.append(f"densidade alta de em-dash ({em_dashes})")

    # 4. Estrutura listicle vazia: muitos bullets sem especificidade técnica.
    bullets = len(BULLET_RE.findall(body))
    has_tech = bool(TECHNICAL_TOKENS_RE.search(full)) or bool(
        MODEL_NAME_RE.search(full)
    )
    if bullets >= 4 and not has_tech:
        points += 0.25
        reasons.append(f"listicle com {bullets} bullets sem especificidade")

    # 5. Falta de especificidade técnica em texto longo.
    if n_words >= LONG_TEXT_WORDS and not has_tech:
        points += 0.25
        reasons.append(
            f"texto longo ({n_words} palavras) sem termos técnicos concretos"
        )

    # 6. Texto curto + título clickbait + corpo genérico.
    if CLICKBAIT_RE.search(title):
        points += 0.15
        reasons.append("título clickbait")
        if n_words < 60 and not has_tech:
            points += 0.15
            reasons.append("corpo curto e genérico sob título clickbait")

    score = min(points, 1.0)
    # Se houve especificidade técnica clara, atenua o sinal de texto: posts
    # técnicos reais não devem ser barrados só pela heurística de texto.
    if has_tech and score > 0.3:
        score *= 0.5
        reasons.append("(atenuado: presença de termos técnicos concretos)")

    if not reasons:
        return 0.0, reasons
    return score, reasons


# ---------------------------------------------------------------------------
# API PÚBLICA
# ---------------------------------------------------------------------------

def is_slop(post: dict) -> tuple[bool, float, list[str]]:
    """Avalia se um post é majoritariamente slop.

    Args:
        post: dict do post com (pelo menos) `title`, `body_md`, `top_comments`.

    Returns:
        (eh_slop, score_slop_0a1, razões):
          - eh_slop: True se score >= SLOP_THRESHOLD.
          - score_slop_0a1: score combinado 0..1.
          - razões: lista de strings explicando os sinais detectados.
    """
    if not isinstance(post, dict):
        return False, 0.0, []

    comment_score, comment_reasons = _comment_signal(post.get("top_comments"))
    text_score, text_reasons = _text_signal(
        post.get("title"), post.get("body_md")
    )

    final_score = COMMENT_WEIGHT * comment_score + TEXT_WEIGHT * text_score

    reasons: list[str] = []
    if comment_reasons:
        reasons.append(f"[comentários {comment_score:.2f}] " + "; ".join(comment_reasons))
    if text_reasons:
        reasons.append(f"[texto {text_score:.2f}] " + "; ".join(text_reasons))

    eh_slop = final_score >= SLOP_THRESHOLD
    return eh_slop, round(final_score, 3), reasons
